package link.bek.poc.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.remote.Remotable
public class Vacation implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("From")
   private java.util.Date from;
   @org.kie.api.definition.type.Label("To")
   private java.util.Date to;
   @org.kie.api.definition.type.Label("Description")
   private java.lang.String description;
   @org.kie.api.definition.type.Label("Approver")
   private java.lang.String approver;
   @org.kie.api.definition.type.Label("Status")
   private java.lang.String status;

   @org.kie.api.definition.type.Label(value = "Vacation Identifier")
   private java.lang.String _id;

   @org.kie.api.definition.type.Label(value = "Employee Identifier")
   private java.lang.String employee;

   public Vacation()
   {
   }

   public java.util.Date getFrom()
   {
      return this.from;
   }

   public void setFrom(java.util.Date from)
   {
      this.from = from;
   }

   public java.util.Date getTo()
   {
      return this.to;
   }

   public void setTo(java.util.Date to)
   {
      this.to = to;
   }

   public java.lang.String getDescription()
   {
      return this.description;
   }

   public void setDescription(java.lang.String description)
   {
      this.description = description;
   }

   public java.lang.String getApprover()
   {
      return this.approver;
   }

   public void setApprover(java.lang.String approver)
   {
      this.approver = approver;
   }

   public java.lang.String getStatus()
   {
      return this.status;
   }

   public void setStatus(java.lang.String status)
   {
      this.status = status;
   }

   public java.lang.String get_id()
   {
      return this._id;
   }

   public void set_id(java.lang.String _id)
   {
      this._id = _id;
   }

   public java.lang.String getEmployee()
   {
      return this.employee;
   }

   public void setEmployee(java.lang.String employee)
   {
      this.employee = employee;
   }

   public Vacation(java.util.Date from, java.util.Date to,
         java.lang.String description, java.lang.String approver,
         java.lang.String status, java.lang.String _id, java.lang.String employee)
   {
      this.from = from;
      this.to = to;
      this.description = description;
      this.approver = approver;
      this.status = status;
      this._id = _id;
      this.employee = employee;
   }
   
   @Override
   public String toString() {
      return "Vacation [vacationId=" + _id + ", from=" + from + ", to=" + to + ", status=" + status + "]";
   }

}