package link.bek.poc.model;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.remote.Remotable
public class Vacation implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("From")
   private java.util.Date from;
   @org.kie.api.definition.type.Label("To")
   private java.util.Date to;

   @org.kie.api.definition.type.Label("Description")
   private java.lang.String description;
   @org.kie.api.definition.type.Label("Manager")
   private java.lang.String manager;
   @org.kie.api.definition.type.Label("Status")
   private java.lang.String status;

   @org.kie.api.definition.type.Label(value = "Vacation Identifier")
   private java.lang.String _id;

   @org.kie.api.definition.type.Label(value = "Employee Identifier")
   private java.lang.String employee;
   
   @org.kie.api.definition.type.Label("Request Identifier")
   private java.lang.Long requestId;

   public Vacation()
   {
   }
   

   @Override
   public int hashCode() {
       final int prime = 31;
       int result = 1;
       result = prime * result + ((_id == null) ? 0 : _id.hashCode());
       result = prime * result + ((employee == null) ? 0 : employee.hashCode());
       result = prime * result + ((from == null) ? 0 : from.hashCode());
       result = prime * result + ((requestId == null) ? 0 : requestId.hashCode());
       result = prime * result + ((status == null) ? 0 : status.hashCode());
       result = prime * result + ((to == null) ? 0 : to.hashCode());
       return result;
   }
   
   @Override
   public boolean equals(Object obj) {
       if (this == obj)
           return true;
       if (obj == null)
           return false;
       if (getClass() != obj.getClass())
           return false;
       Vacation other = (Vacation) obj;
       if (_id == null) {
           if (other._id != null)
               return false;
       } else if (!_id.equals(other._id))
           return false;
       if (employee == null) {
           if (other.employee != null)
               return false;
       } else if (!employee.equals(other.employee))
           return false;
       if (from == null) {
           if (other.from != null)
               return false;
       } else if (!from.equals(other.from))
           return false;
       if (requestId == null) {
           if (other.requestId != null)
               return false;
       } else if (!requestId.equals(other.requestId))
           return false;
       if (status == null) {
           if (other.status != null)
               return false;
       } else if (!status.equals(other.status))
           return false;
       if (to == null) {
           if (other.to != null)
               return false;
       } else if (!to.equals(other.to))
           return false;
       return true;
   }

   public java.util.Date getFrom()
   {
      return this.from;
   }

   public void setFrom(java.util.Date from)
   {
      this.from = from;
   }

   public java.util.Date getTo()
   {
      return this.to;
   }

   public void setTo(java.util.Date to)
   {
      this.to = to;
   }

   public java.lang.String getDescription()
   {
      return this.description;
   }

   public void setDescription(java.lang.String description)
   {
      this.description = description;
   }

   public java.lang.String getManager()
   {
      return this.manager;
   }

   public void setManager(java.lang.String manager)
   {
      this.manager = manager;
   }

   public java.lang.String getStatus()
   {
      return this.status;
   }

   public void setStatus(java.lang.String status)
   {
      this.status = status;
   }

   public java.lang.String get_id()
   {
      return this._id;
   }

   public void set_id(java.lang.String _id)
   {
      this._id = _id;
   }

   public java.lang.String getEmployee()
   {
      return this.employee;
   }

   public void setEmployee(java.lang.String employee)
   {
      this.employee = employee;
   }

   public java.lang.Long getRequestId()
   {
      return this.requestId;
   }

   public void setRequestId(java.lang.Long requestId)
   {
      this.requestId = requestId;
   }

   public Vacation(java.util.Date from, java.util.Date to,
         java.lang.String description, java.lang.String manager,
         java.lang.String status, java.lang.String _id, java.lang.String employee, java.lang.Long requestId)
   {
      this.from = from;
      this.to = to;
      this.description = description;
      this.manager = manager;
      this.status = status;
      this._id = _id;
      this.employee = employee;
      this.requestId = requestId;
   }
   
   @Override
   public String toString() {
      Gson gson = new GsonBuilder().setDateFormat("dd-MM-yyyy").create();
      return gson.toJson(this);
   }

}

